r"""Probe 0a of .claude/plans/bonsai-2-ternary.md: the 2-bit (ternary) GEMV against
the q4_1 one on the SAME dataflow, so the only differences are the tile function
and the chunk size.

    y[N] = W[N, K] @ x[K]

GEMV_FMT=t2: gemv_t2.h, 2176 B chunks (2-bit codes, a bf16 scale per 128 K).
GEMV_FMT=t2g: the same chunks with GEMV_T2_G128 (one activation exponent per 128 K,
the float epilogue once per weight group).
GEMV_FMT=t2h: t2g plus GEMV_T2_FWHT (the 1024-wide Walsh-Hadamard on x in the prep).
GEMV_FMT=q4: gemv_q4.h, 5120 B chunks (q4_1). t2_pack.py writes the same ternary
weights both ways, so both builds must produce the same y.

Dataflow (gemv_q4.py's): n_cores workers, each fed its contiguous slice of bands
by its own shim stream in elements of PER_CALL chunks (double-buffered in L1); x
broadcast once; one 64-float result per band. Unlike gemv_q4.py there is ONE
kernel entry per core with the chunk group as a runtime argument, so K = 5120 and
8192 (the 27B's widths) need no per-group entry points.

Shape via env: GEMV_FMT, GEMV_N, GEMV_K, GEMV_PER_CALL (default 4 for t2, 2 for q4:
q4 at PER_CALL 4 and K 5120 overflows the 64 KB of L1), GEMV_NULL=1 (DMA only).

Build (WSL):  python build_design.py designs/gemv_t2/gemv_t2.py designs/gemv_t2/build_<fmt>_<shape>
Test vectors: (cd designs/gemv_t2 && python make_test.py --shape gate)
"""

from __future__ import annotations

import hashlib
import os
from pathlib import Path

import numpy as np
from ml_dtypes import bfloat16

import aie.iron as iron
from aie.iron import Buffer, CompileTime, In, ObjectFifo, Out, Program, Runtime, TaskGroup, Worker
from aie.iron.controlflow import range_
from aie.iron.kernel import ExternalFunction
from aie.helpers.taplib import TensorAccessPattern, TensorTiler2D
from aie.utils import config

HERE = Path(__file__).parent
Q4 = HERE.parent / "gemv_q4"

TILE_BYTES = {"t2": 2176, "t2g": 2176, "t2h": 2176, "t2p": 2176, "q4": 5120}
G128 = ("t2g", "t2h")
FMT = os.environ.get("GEMV_FMT", "t2")
N = int(os.environ.get("GEMV_N", 17408))
K = int(os.environ.get("GEMV_K", 5120))
RS = 2
N_CORES = int(os.environ.get("GEMV_CORES", 8))
PER_CALL = int(os.environ.get("GEMV_PER_CALL", 2 if FMT == "q4" else 4))
NULL = int(os.environ.get("GEMV_NULL", 0))
EXTRA = os.environ.get("GEMV_CFLAGS", "")


def _include_dirs() -> list[str]:
    from aie.iron.kernels._common import _detect_arch, _include_dirs as base

    inc = base()
    root = Path(config.cxx_header_path()) / "aie_kernels"
    inc += [str(root), str(root / _detect_arch()), str(HERE), str(Q4)]
    return inc


def _write(p: Path, src: str) -> Path:
    if not p.is_file() or p.read_text(encoding="utf-8") != src:
        p.write_text(src, encoding="utf-8", newline="\n")
    return p


def ensure_entry(fmt: str, per_call: int, per_band: int, rs: int) -> tuple[str, Path]:
    if fmt == "t2p":
        # the PRODUCTION body (designs/gemv_q4/gemv_t2.h, what the 27B's lx / ax run) at the
        # probe's unpadded 2176 B chunks; GEMV_T2_OUNROLL comes in through GEMV_CFLAGS
        sym = f"gemv_t2p_p{per_call}b{per_band}r{rs}_g"
        src = ("// GENERATED by gemv_t2.py: the production t2 body, chunk groups as a runtime argument.\n"
               f"#define GEMV_PER_CALL {per_call}\n#define GEMV_T2_CHUNK 2176\n"
               '#include "../gemv_q4/gemv_t2.h"\n\nextern "C" {\n'
               f"void {sym}(const uint8_t *__restrict t, const uint8_t *__restrict tab, float *__restrict y,\n"
               "           int32_t group, int32_t band) {\n"
               "  (void)band;\n"
               f"  for (unsigned sub = 0; sub < {per_call}u; ++sub)\n"
               f"    gemv_t2_chunk_rt(t, tab, (unsigned)group, {per_band}u | (sub << 16), y, {rs}u);\n"
               "}\n}\n")
        return sym, _write(HERE / f"{sym}.cc", src)
    base = "q4" if fmt == "q4" else "t2"
    sym = f"gemv_{base}_p{per_call}b{per_band}r{rs}_g"
    hdr, macro = ("gemv_q4.h", "GEMV_Q4_GROUP_ENTRY") if fmt == "q4" else ("gemv_t2.h", "GEMV_T2_GROUP_ENTRY")
    src = (f"// GENERATED by gemv_t2.py: {fmt} band chunk groups as a runtime argument.\n"
           f"#define GEMV_PER_CALL {per_call}\n#define GEMV_PER_BAND {per_band}\n#define GEMV_ROWSPLIT {rs}\n"
           f'#include "{hdr}"\n\nextern "C" {{\n{macro}()\n}}\n')
    return sym, _write(HERE / f"{sym}.cc", src)


def ensure_prep(k: int, fmt: str) -> tuple[str, Path]:
    if fmt == "t2p":
        sym = f"gemv_t2p_prep_k{k}"
        src = (f"// GENERATED by gemv_t2.py: the production per-128 table for bf16[{k}].\n"
               '#include "../gemv_q4/gemv_t2.h"\n\nextern "C" {\n'
               f"void {sym}(const bfloat16 *__restrict x, uint8_t *__restrict tab) {{\n"
               f"  gemv_t2_prep_groups(x, tab, {k}u, 0u, {k // 128}u);\n"
               "}\n}\n")
        return sym, _write(HERE / f"{sym}.cc", src)
    if fmt in G128:
        sym = f"gemv_t2_prep_k{k}"
        src = (f"// GENERATED by gemv_t2.py: the per-128 activation table for bf16[{k}].\n"
               f'#include "gemv_t2.h"\n\nextern "C" {{\nGEMV_T2_PREP_ENTRY({k})\n}}\n')
        return sym, _write(HERE / f"{sym}.cc", src)
    sym = f"gemv_q4_prep_k{k}"
    src = (f"// GENERATED by gemv_t2.py: block-quantise a bf16[{k}] activation into the GEMV table.\n"
           f'#include "gemv_tab.h"\n\nextern "C" {{\nGEMV_Q4_PREP_ENTRY({k})\n}}\n')
    return sym, _write(HERE / f"t2probe_prep_k{k}.cc", src)


def tab_bytes(k: int, fmt: str) -> int:
    return 2 * k + k // 16 if fmt in G128 or fmt == "t2p" else 2 * k + k // 8 + k // 8


@iron.jit(aiecc_flags=["--alloc-scheme=basic-sequential"])
def gemv_t2(w: In, x: In, y: Out, *, fmt: CompileTime[str], n: CompileTime[int], k: CompileTime[int],
            rs: CompileTime[int], n_cores: CompileTime[int], per_call: CompileTime[int],
            null: CompileTime[int] = 0, srchash: CompileTime[int] = 0, cflags: CompileTime[str] = ""):
    tile = TILE_BYTES[fmt]
    band_rows = 32 * rs
    per_band = rs * k // 256
    assert per_band % per_call == 0
    n_groups = per_band // per_call
    bands = n // band_rows
    assert n % band_rows == 0 and bands % n_cores == 0
    bands_per_core = bands // n_cores
    band_bytes = per_band * tile

    sym, src = ensure_entry(fmt, per_call, per_band, rs)
    psym, psrc = ensure_prep(k, fmt)
    vflags = (["-DGEMV_T2_G128"] if fmt in G128 else []) + (["-DGEMV_T2_FWHT"] if fmt == "t2h" else [])
    elem_ty = np.ndarray[(per_call * tile,), np.dtype[np.uint8]]
    x_ty = np.ndarray[(k,), np.dtype[bfloat16]]
    tab_ty = np.ndarray[(tab_bytes(k, fmt),), np.dtype[np.uint8]]
    acc_ty = np.ndarray[(band_rows,), np.dtype[np.float32]]
    w_ty = np.ndarray[(bands * band_bytes,), np.dtype[np.uint8]]
    y_ty = np.ndarray[(n,), np.dtype[np.float32]]

    fn = ExternalFunction(sym, source_file=str(src), arg_types=[elem_ty, tab_ty, acc_ty, np.int32, np.int32],
                          include_dirs=_include_dirs(),
                          compile_flags=(["-DGEMV_NULL"] if null else []) + vflags + cflags.split())
    prep = ExternalFunction(psym, source_file=str(psrc), arg_types=[x_ty, tab_ty],
                            include_dirs=_include_dirs(), compile_flags=vflags + cflags.split())

    of_w = [ObjectFifo(elem_ty, name=f"w{c}", depth=2) for c in range(n_cores)]
    of_y = [ObjectFifo(acc_ty, name=f"y{c}", depth=2) for c in range(n_cores)]
    of_x = ObjectFifo(x_ty, name="x", depth=1)

    def core_body(win, xin, yout, tab, fprep, fgemv):
        xe = xin.acquire(1)
        fprep(xe, tab)
        for _ in range_(bands_per_core):
            ye = yout.acquire(1)
            for g in range_(n_groups):
                we = win.acquire(1)
                fgemv(we, tab, ye, g, 0)
                win.release(1)
            yout.release(1)
        xin.release(1)

    workers = [
        Worker(core_body,
               fn_args=[of_w[c].cons(), of_x.cons(), of_y[c].prod(), Buffer(tab_ty, name=f"tab{c}"), prep, fn],
               stack_size=0x1000)
        for c in range(n_cores)
    ]

    w_taps = TensorTiler2D.simple_tiler((1, bands * band_bytes), (1, bands_per_core * band_bytes))
    y_taps = [TensorAccessPattern((1, n), c * bands_per_core * band_rows,
                                  [1, 1, 1, bands_per_core * band_rows], [0, 0, 0, 1]) for c in range(n_cores)]

    def sequence(a_w, a_x, c_y, w_prods, x_prod, y_conss):
        tg = TaskGroup()
        x_prod.fill(a_x, group=tg)
        for c in range(n_cores):
            w_prods[c].fill(a_w, tap=w_taps[c], group=tg)
            y_conss[c].drain(c_y, tap=y_taps[c], wait=True, group=tg)
        tg.finish()

    rt = Runtime(sequence, [w_ty, x_ty, y_ty,
                            [f.prod() for f in of_w], of_x.prod(), [f.cons() for f in of_y]])
    return Program(iron.get_current_device(), rt, workers=workers).resolve_program()


DESIGN = gemv_t2
# The jit cache keys on this file + CompileTime args only: hash the headers in.
_SRCHASH = int(hashlib.sha1(b"".join((d / h).read_bytes() for d, h in
                                     [(HERE, "gemv_t2.h"), (Q4, "gemv_q4.h"), (Q4, "gemv_tab.h")])).hexdigest()[:8], 16)
SPECIALIZE = {"fmt": FMT, "n": N, "k": K, "rs": RS, "n_cores": N_CORES, "per_call": PER_CALL,
              "null": NULL, "srchash": _SRCHASH, "cflags": EXTRA}
