// GENERATED by gemm_q4_prefill.py: dequant entry, ky=2
#include "gemm_q4_dequant.h"

extern "C" {
void gqd_entry_k2(const uint8_t *__restrict band, uint8_t *__restrict nib_scr,
                     bfloat16 *__restrict scratch) {
  gqd_dequant_ky(band, 2u, nib_scr, scratch);
}
}
