// GENERATED by gemm_q4_prefill.py: dequant entry, ky=0, bfp16 A (GQP_XBFP)
#include "gemm_q4_dequant.h"

extern "C" {
void gqd_entry_k0(const uint8_t *__restrict band, uint8_t *__restrict nib_scr,
                     bfp16ebs8 *__restrict scratch) {
  gqd_dequant_ky_bfp(band, 0u, nib_scr, scratch);
}
}
