name: CMake Configure, Build, Test

on:
  push:
    branches: [ "main","feat/**","bugfix/**" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Pulls
      uses: actions/checkout@v4

    - name: Submodules
      uses: snickerbockers/submodules-init@v4
    
    - name: Sets up Ninja-build
      uses: wirekang/setup-ninja@v1
      with:
        platform: linux

    - name: Installs Deps
      uses: gerlero/apt-install@v1.3.12
      with:
        packages: libxrt-dev uuid-dev libreadline-dev libboost-all-dev libcurl4-openssl-dev libfftw3-dev libavformat-dev libavcodec-dev libavutil-dev libswscale-dev libswresample-dev
        cache: true
        install-recommends: true

    - name: Configures OpenFlowLM
      run: cmake -B ${{github.workspace}}/build --preset linux-${{env.BUILD_TYPE}} -G Ninja

    - name: Builds
      run: source /opt/xilinx/xrt/setup.sh && cmake --build ${{github.workspace}}/build

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest --preset linux-default
