r"""Batched q4_1 GEMM on the NPU: Y[M, K] rows against W[N, K] pool chunks.

Same dataflow as designs/gemv_q4, with an M dimension: each core still streams
its slice of the weight bands once, but now keeps M activation tables and emits
M band accumulators per band. The weight DMA per band is unchanged, so time vs
M measures how much compute headroom sits under the weight stream - which is
what decides whether NPU prefill can beat the iGPU.

GEMM_BLOCKED=1 switches to the blocked dataflow: the weights arrive k-tile-major
and every band's accumulator stays resident, so the per-token table is one
256-wide slice (576 B) instead of the whole K (4608 B) and M reaches 24 instead
of 8. Weight bytes per pass are the same either way; what changes is how many
tokens ride along. Needs GEMM_PER_CALL=1 and make_test.py --blocked.

Shape via env GEMM_N / GEMM_K / GEMM_RS / GEMM_CORES / GEMM_M.

Build (WSL):  GEMM_M=4 python build_design.py designs/gemm_q4/gemm_q4.py designs/gemm_q4/build_m4
Run:          (cd designs/gemm_q4 && run_kernel run_m4.cfg)   (see make_test.py)
"""

from __future__ import annotations

import hashlib
import os
from pathlib import Path

import numpy as np
from ml_dtypes import bfloat16

import aie.iron as iron
from aie.iron import Buffer, CompileTime, In, ObjectFifo, Out, Program, Runtime, TaskGroup, Worker
from aie.iron.controlflow import range_
from aie.iron.kernel import ExternalFunction
from aie.helpers.taplib import TensorAccessPattern, TensorTiler2D
from aie.utils import config

HERE = Path(__file__).parent
GEMV = HERE.parent / "gemv_q4"

TILE_BYTES = 5120
Q4K_TILE_BYTES = 4736   # Q4_K-native chunk: bf16 d/dmin + 6-bit sc/mn + nibbles

N = int(os.environ.get("GEMM_N", 8192))
K = int(os.environ.get("GEMM_K", 2048))
RS = int(os.environ.get("GEMM_RS", 2))
N_CORES = int(os.environ.get("GEMM_CORES", 8))
M = int(os.environ.get("GEMM_M", 4))
PER_CALL = int(os.environ.get("GEMM_PER_CALL", 4))   # chunks per DMA element; 2 frees 20 KB of L1 for larger M
NULL = int(os.environ.get("GEMM_NULL", 0))
BLOCKED = int(os.environ.get("GEMM_BLOCKED", 0))  # k-tile-major weights, all bands resident
TAB_IL = int(os.environ.get("GEMM_TAB_IL", 0))    # token-interleaved activation table
INT8 = int(os.environ.get("GEMM_INT8", 0))        # int8 activations, mmul<8,8,8>; implies TAB_IL
BPT = int(os.environ.get("GEMM_BPT", 0))          # bands per output tile (0 = all of them)
G128 = int(os.environ.get("GEMM_G128", 0))        # TIMING PROBE: scales every 128, not 32
Q4K = int(os.environ.get("GEMM_Q4K", 0))          # Q4_K chunks, sub-scales folded into int32; implies TAB_IL
PREQ = int(os.environ.get("GEMM_PREQ", 0))        # stream an already-quantised IL table from the host
EXTRA = os.environ.get("GEMM_CFLAGS", "")


def _include_dirs() -> list[str]:
    from aie.iron.kernels._common import _detect_arch, _include_dirs as base

    inc = base()
    root = Path(config.cxx_header_path()) / "aie_kernels"
    inc.append(str(root))
    inc.append(str(root / _detect_arch()))
    inc.append(str(GEMV))
    return inc


def tab_bytes(k: int) -> int:
    return 2 * k + k // 4


def il_group_bytes(k_tile: int = 256, group: int = 4) -> int:
    return group * tab_bytes(k_tile)


def ensure_prep_entry(k: int, m: int) -> Path:
    p = HERE / f"gemm_q4_prep_k{k}m{m}.cc"
    src = (
        f"// GENERATED by gemm_q4.py: block-quantise {m} bf16[{k}] activations.\n"
        f"#define GEMM_BATCH {m}\n"
        f'#include "gemm_q4.h"\n\n'
        f'extern "C" {{\n'
        f"GEMM_Q4_PREP_ENTRY({k})\n"
        f"}}\n"
    )
    if not p.is_file() or p.read_text(encoding="utf-8") != src:
        p.write_text(src, encoding="utf-8", newline="\n")
    return p


def ensure_blk_sources(per_call: int, per_band: int, rs: int, m: int) -> tuple[Path, Path]:
    tile = HERE / f"gemm_q4_blk_p{per_call}b{per_band}r{rs}m{m}.cc"
    src = (
        f"// GENERATED by gemm_q4.py: blocked-dataflow chunk group of {per_call}, "
        f"{per_band}-chunk band, row split {rs}, batch {m}.\n"
        f"#define GEMV_PER_CALL {per_call}\n"
        f"#define GEMV_PER_BAND {per_band}\n"
        f"#define GEMV_ROWSPLIT {rs}\n"
        f"#define GEMM_BATCH {m}\n"
        f'#include "gemm_q4.h"\n\n'
        f'extern "C" {{\n'
        f"GEMM_Q4_BLK_ENTRY()\n"
        f"}}\n"
    )
    if not tile.is_file() or tile.read_text(encoding="utf-8") != src:
        tile.write_text(src, encoding="utf-8", newline="\n")

    prep = HERE / f"gemm_q4_prep_slice_m{m}.cc"
    src = (
        f"// GENERATED by gemm_q4.py: block-quantise one k-tile slice into slot m of {m}.\n"
        f"#define GEMM_BATCH {m}\n"
        f'#include "gemm_q4.h"\n\n'
        f'extern "C" {{\n'
        f"GEMM_Q4_PREP_SLICE_ENTRY()\n"
        f"}}\n"
    )
    if not prep.is_file() or prep.read_text(encoding="utf-8") != src:
        prep.write_text(src, encoding="utf-8", newline="\n")
    return tile, prep


def ensure_copy_source(m: int) -> Path:
    # GEMM_PREQ: no arithmetic, just gemm_q4_copy_group_m{M} landing an
    # already-quantised IL group straight into `tab`.
    p = HERE / f"gemm_q4_copy_slice_m{m}.cc"
    src = (
        f"// GENERATED by gemm_q4.py: copy one pre-quantised IL group into slot g of {m}.\n"
        f"#define GEMM_BATCH {m}\n"
        f'#include "gemm_q4.h"\n\n'
        f'extern "C" {{\n'
        f"GEMM_Q4_COPY_GROUP_ENTRY()\n"
        f"}}\n"
    )
    if not p.is_file() or p.read_text(encoding="utf-8") != src:
        p.write_text(src, encoding="utf-8", newline="\n")
    return p


def ensure_entry_points(n_entry: int, per_call: int, per_band: int, rs: int, m: int) -> list[Path]:
    out = []
    for i in range(n_entry):
        p = HERE / f"gemm_q4_p{per_call}b{per_band}r{rs}m{m}_k{i}.cc"
        src = (
            f"// GENERATED by gemm_q4.py: band chunk group {i} of a {per_band}-chunk band, "
            f"row split {rs}, batch {m}.\n"
            f"#define GEMV_PER_CALL {per_call}\n"
            f"#define GEMV_PER_BAND {per_band}\n"
            f"#define GEMV_ROWSPLIT {rs}\n"
            f"#define GEMM_BATCH {m}\n"
            f'#include "gemm_q4.h"\n\n'
            f'extern "C" {{\n'
            f"GEMM_Q4_ENTRY({i})\n"
            f"}}\n"
        )
        if not p.is_file() or p.read_text(encoding="utf-8") != src:
            p.write_text(src, encoding="utf-8", newline="\n")
        out.append(p)
    return out


@iron.jit(aiecc_flags=["--alloc-scheme=basic-sequential"])
def gemm_q4(w: In, x: In, y: Out, *, n: CompileTime[int], k: CompileTime[int],
            rs: CompileTime[int], n_cores: CompileTime[int], per_call: CompileTime[int],
            m: CompileTime[int] = 4, null: CompileTime[int] = 0, blocked: CompileTime[int] = 0,
            tab_il: CompileTime[int] = 0, int8: CompileTime[int] = 0,
            bpt: CompileTime[int] = 0, g128: CompileTime[int] = 0,
            q4k: CompileTime[int] = 0, preq: CompileTime[int] = 0,
            srchash: CompileTime[int] = 0, cflags: CompileTime[str] = ""):
    band_rows = 32 * rs
    per_band = rs * k // 256
    n_entry = per_band // per_call
    assert per_band % per_call == 0
    tile_bytes = Q4K_TILE_BYTES if q4k else TILE_BYTES
    bands = n // band_rows
    assert n % band_rows == 0 and bands % n_cores == 0, (n, n_cores)
    bands_per_core = bands // n_cores
    band_bytes = per_band * tile_bytes
    call_bytes = per_call * tile_bytes

    n_kt = per_band // rs                         # k-tiles per band
    core_floats = m * bands_per_core * band_rows      # y floats per core per pass

    elem_ty = np.ndarray[(call_bytes,), np.dtype[np.uint8]]
    w_ty = np.ndarray[(bands * band_bytes,), np.dtype[np.uint8]]
    if preq:
        assert blocked and (tab_il or q4k) and not int8, \
            "GEMM_PREQ needs GEMM_BLOCKED with GEMM_TAB_IL or GEMM_Q4K, no GEMM_INT8"
        assert m % 4 == 0, (m,)
        # [n_kt][m/4][kILGroupBytes], the exact order the core reads it in -
        # the host has already run gemm_q4_prep_il's arithmetic once.
        x_ty = np.ndarray[(n_kt * (m // 4) * il_group_bytes(),), np.dtype[np.uint8]]
    else:
        x_ty = np.ndarray[(m * k,), np.dtype[bfloat16]]
    y_ty = np.ndarray[(m * n,), np.dtype[np.float32]]

    if blocked:
        # per_call trades shim transfer count for L1 - each extra chunk per
        # element is another 5 KB of double buffer, and L1 is the M ceiling.
        # Measured: no difference to the floor at 1, 2 or 4.
        assert (bands_per_core * rs) % per_call == 0, (bands_per_core, rs, per_call)
        # int8 packs eight tokens per mmul and 320 B per token; the interleaved
        # int16 table is four per mmul and 576 B. Both want M a multiple of the
        # group so the last group is full.
        group = 8 if int8 else 4
        slice_bytes = 320 if int8 else tab_bytes(256)
        assert m % group == 0 or m == 1, (m, group)
        # int8 preps two tokens per call: the smallest int8 vector store is 16
        # lanes and one token's k-octet is 8, so the pair goes down together.
        x_tok = 2 if int8 else 1
        if preq:
            x_one_ty = np.ndarray[(il_group_bytes(),), np.dtype[np.uint8]]
        else:
            x_one_ty = np.ndarray[(x_tok * 256,), np.dtype[bfloat16]]
        tab_ty = np.ndarray[(m * slice_bytes,), np.dtype[np.uint8]]
        # Output tiling: a core holds the accumulators for `bpt` of its bands
        # instead of all of them, which is what lets M grow. The activations are
        # re-broadcast per tile - one shim stream feeds all 32 cores, so that is
        # n_tiles x n_kt x M x 512 B against the whole 10.5 MB of weights.
        bpt_ = bpt or bands_per_core
        assert bands_per_core % bpt_ == 0, (bands_per_core, bpt_)
        n_tiles = bands_per_core // bpt_
        assert n_tiles <= 4, "a shim channel's start queue holds 4 BDs"
        # The y element IS the resident accumulator block - all of the core's
        # bands for all M tokens - so it is acquired once and drained at the end
        # of the pass. Depth 1: two of these do not fit L1.
        acc_floats = m * bpt_ * band_rows             # one output tile per element
        acc_ty = np.ndarray[(acc_floats,), np.dtype[np.float32]]
        # Depth 2 lets tile i's drain overlap tile i+1's compute, at the cost
        # of a second accumulator block in L1 - which at bpt = 1 is the single
        # biggest per-token resident after the table. GEMM_ACC_DEPTH=1 trades
        # that overlap for M (the L1 model says 40 -> 52 at bpt = 1).
        acc_depth = (int(os.environ.get("GEMM_ACC_DEPTH", 0)) or 2) if n_tiles > 1 else 1
        x_depth = 2

        variant = (["-DGEMM_TAB_IL"] if (tab_il or int8 or q4k) else []) + \
                  (["-DGEMM_INT8"] if int8 else []) + \
                  (["-DGEMM_G128"] if g128 else []) + \
                  (["-DGEMM_Q4K"] if q4k else [])
        # eight live accumulators and a ve/vo array twice the size: 4 KB
        # overflows the stack and the core hangs (ERT state 8)
        # int8 needs 0x2000 (eight live accumulators and a doubled ve/vo array);
        # q4k keeps 0x1000 - its k loop holds four int32 accumulators and no
        # per-token array - and spends the difference on the sub-scale scratch.
        stack = 0x2000 if int8 else 0x1000
        tile_src, prep_src = ensure_blk_sources(per_call, per_band, rs, m)
        ftile = ExternalFunction(
            f"gemm_q4_blk_p{per_call}b{per_band}r{rs}m{m}", source_file=str(tile_src),
            arg_types=[elem_ty, tab_ty, acc_ty, np.int32, np.int32],
            include_dirs=_include_dirs(),
            compile_flags=(["-DGEMV_NULL"] if null else []) + variant + cflags.split())
        if preq:
            # No arithmetic left in the activation path - gemm_q4_copy_group
            # just lands the host's already-quantised bytes in `tab`.
            copy_src = ensure_copy_source(m)
            fprep = ExternalFunction(
                f"gemm_q4_copy_group_m{m}", source_file=str(copy_src),
                arg_types=[x_one_ty, tab_ty, np.int32], include_dirs=_include_dirs(),
                compile_flags=["-DGEMM_PREQ"] + variant + cflags.split())
        else:
            fprep = ExternalFunction(
                f"gemm_q4_prep_slice_m{m}", source_file=str(prep_src),
                arg_types=[x_one_ty, tab_ty, np.int32], include_dirs=_include_dirs(),
                compile_flags=variant + cflags.split())
        kernel_args = [fprep, ftile]

        if preq:
            # xin's elements are already 4-token IL groups - `mi` here counts
            # groups, not tokens, so the loop is m/4 iterations regardless of
            # x_tok (GEMM_PREQ does not support GEMM_INT8 yet, see the assert
            # above).
            def core_body(win, xin, yout, tab, fcopy, fchunk):
                for _ in range_(n_tiles):
                    ye = yout.acquire(1)
                    for kt in range_(n_kt):
                        for gi in range_(m // 4):
                            xe = xin.acquire(1)
                            fcopy(xe, tab, gi)
                            xin.release(1)
                        for idx in range_(bpt_ * rs // per_call):
                            we = win.acquire(1)
                            fchunk(we, tab, ye, idx, kt)
                            win.release(1)
                    yout.release(1)

            # The host writes [n_kt][m/4][kILGroupBytes] contiguously in
            # exactly this read order, so a straight fill needs no tap.
            x_tap = None
        else:
            def core_body(win, xin, yout, tab, fprep, fchunk):
                for _ in range_(n_tiles):
                    ye = yout.acquire(1)
                    for kt in range_(n_kt):
                        for mi in range_(m // x_tok):
                            xe = xin.acquire(1)
                            fprep(xe, tab, mi)
                            xin.release(1)
                        for idx in range_(bpt_ * rs // per_call):
                            we = win.acquire(1)
                            fchunk(we, tab, ye, idx, kt)
                            win.release(1)
                    yout.release(1)

            # k-tile major: for each k-tile, every token's 256-wide slice. With
            # two tokens per element the pair is not contiguous (they are k
            # apart), so the tap needs all four dimensions.
            x_tap = TensorAccessPattern((1, m * k), 0,
                                        [n_kt, m // x_tok, x_tok, 256],
                                        [256, x_tok * k, k, 1])
        x_fills = n_tiles                            # the same slices, once per tile
    else:
        x_one_ty = np.ndarray[(k,), np.dtype[bfloat16]]
        tab_ty = np.ndarray[(m * tab_bytes(k),), np.dtype[np.uint8]]
        acc_floats = m * band_rows                    # one band, one element per band
        acc_ty = np.ndarray[(acc_floats,), np.dtype[np.float32]]
        acc_depth = 2
        x_depth = 1
        stack = 0x1000

        srcs = ensure_entry_points(n_entry, per_call, per_band, rs, m)
        prep_src = ensure_prep_entry(k, m)
        kernels = [
            ExternalFunction(
                f"gemm_q4_p{per_call}b{per_band}r{rs}m{m}_k{i}",
                source_file=str(srcs[i]),
                arg_types=[elem_ty, tab_ty, acc_ty],
                include_dirs=_include_dirs(),
                compile_flags=(["-DGEMV_NULL"] if null else []) + cflags.split())
            for i in range(n_entry)
        ]
        prep = ExternalFunction(f"gemm_q4_prep_k{k}m{m}", source_file=str(prep_src),
                                arg_types=[x_one_ty, tab_ty, np.int32],
                                include_dirs=_include_dirs(), compile_flags=cflags.split())
        kernel_args = [prep, *kernels]

        def core_body(win, xin, yout, tab, fprep, *ks):
            for mi in range_(m):
                xe = xin.acquire(1)
                fprep(xe, tab, mi)
                xin.release(1)
            for _ in range_(bands_per_core):
                ye = yout.acquire(1)
                for fn in ks:
                    we = win.acquire(1)
                    fn(we, tab, ye)
                    win.release(1)
                yout.release(1)

        x_tap = None
        x_fills = 1

    of_x = ObjectFifo(x_one_ty, name="x", depth=x_depth)

    if n_cores <= 8:
        # Direct: one shim stream per core. The device has 16 shim output
        # channels and this needs n_cores + 1 (the x broadcast), so 8 is the most
        # that both fits and divides the 128 bands.
        of_w = [ObjectFifo(elem_ty, name=f"w{c}", depth=2) for c in range(n_cores)]
        of_y = [ObjectFifo(acc_ty, name=f"y{c}", depth=acc_depth) for c in range(n_cores)]
        workers = [
            Worker(core_body,
                   fn_args=[of_w[c].cons(), of_x.cons(), of_y[c].prod(),
                            Buffer(tab_ty, name=f"tab{c}"), *kernel_args],
                   stack_size=stack)
            for c in range(n_cores)
        ]
        w_taps = TensorTiler2D.simple_tiler((1, bands * band_bytes), (1, bands_per_core * band_bytes))
        # Drained contiguously; y is [core][band][token][row], see check.py.
        y_taps = [TensorAccessPattern((1, m * n), c * core_floats,
                                      [1, 1, 1, core_floats], [0, 0, 0, 1]) for c in range(n_cores)]
        w_hs = [f.prod() for f in of_w]
        y_hs = [f.cons() for f in of_y]
        n_streams = n_cores
    else:
        # Fan-out: one shim stream per column into that column's mem tile, split
        # across the column's cores; results joined back the same way. Nine shim
        # output channels for 32 cores instead of 33.
        n_cols = 8
        assert n_cores % n_cols == 0
        n_rows = n_cores // n_cols
        assert n_rows <= 4
        w_l2_ty = np.ndarray[(n_rows * call_bytes,), np.dtype[np.uint8]]
        y_l2_ty = np.ndarray[(n_rows * acc_floats,), np.dtype[np.float32]]

        of_w_l3l2, of_y_l2l3 = [], []
        w_l2l1 = [[None] * n_rows for _ in range(n_cols)]
        y_l1l2 = [[None] * n_rows for _ in range(n_cols)]
        for c in range(n_cols):
            wf = ObjectFifo(w_l2_ty, name=f"w_l3l2_{c}", depth=2)
            of_w_l3l2.append(wf)
            subs = wf.cons().split([r * call_bytes for r in range(n_rows)],
                                   obj_types=[elem_ty] * n_rows,
                                   names=[f"w_l2l1_{c}_{r}" for r in range(n_rows)],
                                   depths=[2] * n_rows)
            for r in range(n_rows):
                w_l2l1[c][r] = subs[r]

            yf = ObjectFifo(y_l2_ty, name=f"y_l2l3_{c}", depth=2)
            of_y_l2l3.append(yf)
            subs = yf.prod().join([r * acc_floats for r in range(n_rows)],
                                  obj_types=[acc_ty] * n_rows,
                                  names=[f"y_l1l2_{c}_{r}" for r in range(n_rows)],
                                  depths=[acc_depth] * n_rows)
            for r in range(n_rows):
                y_l1l2[c][r] = subs[r]

        workers = Worker.grid(
            n_rows, n_cols,
            lambda row, col: Worker(core_body,
                                    [w_l2l1[col][row].cons(), of_x.cons(), y_l1l2[col][row].prod(),
                                     Buffer(tab_ty, name=f"tab{col}_{row}"), *kernel_args],
                                    stack_size=stack),
        )
        workers = [w for row in workers for w in row]

        # The column's L2 object is one DMA element from each of its n_rows
        # cores, so the weights arrive pre-interleaved at call_bytes granularity
        # (make_test.py writes that order; a backend would repack once at load)
        # and each column streams a contiguous run. A strided host tap doing the
        # interleave on the fly failed in shim BD lowering.
        core_bytes = bands_per_core * band_bytes
        col_bytes = n_rows * core_bytes
        w_taps = [TensorAccessPattern((1, bands * band_bytes), c * col_bytes,
                                      [1, 1, 1, col_bytes], [0, 0, 0, 1]) for c in range(n_cols)]
        # Drained contiguously per column; naive y is [col][band][row][token][64],
        # blocked y is [col][row][band][token][64] - one element per core per pass.
        col_floats = n_rows * core_floats
        y_taps = [TensorAccessPattern((1, m * n), c * col_floats,
                                      [1, 1, 1, col_floats], [0, 0, 0, 1]) for c in range(n_cols)]
        w_hs = [f.prod() for f in of_w_l3l2]
        y_hs = [f.cons() for f in of_y_l2l3]
        n_streams = n_cols

    def sequence(a_w, a_x, c_y, w_prods, x_prod, y_conss):
        tg = TaskGroup()
        for _ in range(x_fills):
            if x_tap is None:
                x_prod.fill(a_x, group=tg)
            else:
                x_prod.fill(a_x, tap=x_tap, group=tg)
        for c in range(n_streams):
            w_prods[c].fill(a_w, tap=w_taps[c], group=tg)
            y_conss[c].drain(c_y, tap=y_taps[c], wait=True, group=tg)
        tg.finish()

    rt = Runtime(sequence, [w_ty, x_ty, y_ty, w_hs, of_x.prod(), y_hs])
    return Program(iron.get_current_device(), rt, workers=workers).resolve_program()


DESIGN = gemm_q4
_SRCHASH = int(hashlib.sha1(
    (HERE / "gemm_q4.h").read_bytes() + (GEMV / "gemv_q4.h").read_bytes()
).hexdigest()[:8], 16)
SPECIALIZE = {"n": N, "k": K, "rs": RS, "n_cores": N_CORES, "per_call": PER_CALL,
              "m": M, "null": NULL, "blocked": BLOCKED, "tab_il": TAB_IL, "int8": INT8,
              "bpt": BPT, "g128": G128, "q4k": Q4K, "preq": PREQ,
              "srchash": _SRCHASH, "cflags": EXTRA}
